######################################################################
#
# File name : cpu_tb_wave.do
# Created on: Thu Nov 07 11:57:03 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
