# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/workspace/vivado/AsmCPU/AsmCPU.srcs/sources_1/ip/Imem/Imem.xci
# IP: The module: 'Imem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/workspace/vivado/AsmCPU/AsmCPU.srcs/sources_1/ip/Imem/Imem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Imem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/workspace/vivado/AsmCPU/AsmCPU.srcs/sources_1/ip/Imem/Imem.xci
# IP: The module: 'Imem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/workspace/vivado/AsmCPU/AsmCPU.srcs/sources_1/ip/Imem/Imem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Imem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
